function [] = stopTrialFig (const)

if const.stopTrialFigVisible == 1
    visibility = 'on';
else
    visibility = 'off';
end


figure
clo.H = set(gcf,'name','CloseTrial',...
            'visible',visibility,...
            'NumberTitle','off',...
            'toolbar','none',...
            'menubar','none',...
            'units','normalized',...
            'OuterPosition',[0.9 0.05 0.1 0.1] );
        
clo.pb = uicontrol('style','push',...
                    'units','normalized',...
                    'position',[0 0 1 1],...
                    'fontsize',30,...
                    'backgroundcolor','r',...
                    'string','Stop',...
                    'val',0,...
                    'callback',{@stp_call,clo});

function [] = stp_call(varargin)
% Callback for pushbutton, deletes one line from listbox.
S = varargin{1};
S.Value = 1;
assignin('base','stopTrial',S.Value)
close
